### DISCUSSION TITLE
Extending schema in v4

### DISCUSSION THREAD

**Discussion by dragomano** [leafsphp/leaf#280] [Ideas]
In v3, I am using such a factory:

```php
public function definition(): array
{
        $title = rtrim($this->faker->sentence, '.');

	return [
            'user_id' => User::all()->random()->id,
            'category_id' => Category::all()->random()->id,
            'slug' => $this->str::slug($title),
            'title' => $title,
            'content' => $this->faker->paragraphs(rand(1, 6), true),
	];
}
```
and such a seeder:

```php
public function run()
{
        (new PostFactory)->create(20)->save();

	$posts = Post::all();
	$tags = Tag::all();

	$posts->each(function ($post) use ($tags) {
		$randomTags = $tags->random(rand(1, 3));
		$post->tags()->attach($randomTags->pluck('id'));
	});
}
```

How to implement this logic in YML schemas in v4?

Something like this? (I know `@model` and `@str` do not exist - I'm just fantasizing)

```yml
columns:
  user_id:
    type: foreign
    onDelete: true
    onUpdate: true
  category_id:
    type: foreign
    onDelete: true
    onUpdate: true
  slug:
    type: string
    length: 255
    unique: true
  title: string
  content: string

relationships:
  - User
  - Category

seeds:
  count: 20
  truncate: true
  data:
    user_id: '@model(user).random'
    category_id: '@model(category).random'
    slug: '@str.slug(title)'
    title: '@faker->sentence'
    content: '@faker.paragraphs(rand(1, 6), true)'

```
